# Railway service configuration for musda-backend
# Refer: https://docs.railway.app/reference/railway-toml

[build]
# backend only
builder = "NIXPACKS"

[deploy]
# IMPORTANT: Do NOT auto-run migrations here; DB plugin may not be ready instantly and will cause ECONNREFUSED loops.
# After first successful deploy and DB readiness, run migrations manually with:
#   railway run npm run sql:migrate
# If you really want to chain them once, temporarily set:
#   startCommand = "npm run sql:migrate && npm start"
# Then revert to plain start afterwards.
startCommand = "npm start"  # Simplified: manual one-time migration will be triggered separately
root = "./backend"

[env]
# (Optional) Set these only while you still need manual migration endpoint.
# ALLOW_MANUAL_MIGRATION = "1"
# MIGRATION_DB_CONNECT_ATTEMPTS = "15"
# MIGRATION_DB_CONNECT_DELAY_MS = "4000"
# If you prefer using public proxy values, uncomment and fill below (or set via Railway Dashboard):
# DB_HOST = "shuttle.proxy.rlwy.net"
# DB_PORT = "<proxy_port>"
# DB_USER = "<db_user>"
# DB_PASSWORD = "<db_password>"
# DB_NAME = "<db_name>"

[health]
path = "/api/health"
interval = 10
timeout = 3
retries = 10
